server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: movie-service
              uri: lb://MOVIE-SERVICE
              predicates:
                - Path=/movies/**

            - id: booking-service
              uri: lb://BOOKING-SERVICE
              predicates:
                - Path=/bookings/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 1.0
